"""S1 — tip-first sweep, following Openblademesh faithfully.

Source: Michael A. Heider, *Create an Automated Structured Mesh Generation Method
for Rotor Blades using Exclusively Open Source Software*, Bachelor Thesis, IAG
Universität Stuttgart, September 2023 —
`papers/Openblademesh_Bachelor_Thesis_Michael_Heider_Abgabe_noBK.pdf`.
Read in full; the construction below follows §3.1.4 (Section3: Wingtip generation)
and its code listing, with §§1.1.2, 1.1.4, 3.1.5, 3.1.7 and 4.2 informing the rest.

================================================================================
WHAT THE PAPER STATES
================================================================================

**The inner airfoil (§3.1.4, code line 273: `X = 0.33`).** "The boundaries of the
inner airfoil are generated by taking the difference between the upper and lower
airfoil and either substituting or adding a fraction of this value to the original
point... The result is then multiplied by 1/3 and substituted from the first value.
This results in an inner airfoil that is a third the size of the original airfoil
and follows the shape of the first airfoil very precisely, **even in concave
areas**."

    inner_upper(x) = zu(x) - X * (zu(x) - zl(x))
    inner_lower(x) = zl(x) + X * (zu(x) - zl(x))         X = 0.33

Same convex-combination family COMMON_BRIEF §1 arrived at independently, here at
``width_frac = 1 - 2X = 0.34``. The paper's justification is the one that matters:
it follows the section even where the section is concave.

**The 45-degree rule (§3.1.4).** "The points for the end of the splines are created
so that the connection lines from these to the outer airfoil are **45 degrees**. The
45 degrees are important because they allow for the most regular translation of
cells on each side of the connecting line."

Code lines 403-407 give the two end stations:

    x_te_end   = x(inner aft) - 1/4 * te_thickness          (line 403)
    x_nose_end = sqrt(2) * 0.003 * chord                    (line 407)

The sqrt(2) is the 45-degree factor. Both end regions are therefore **tiny** — about
0.0042 chord at the nose against a 0.005-chord blunt base. That is what lets the
nose domain and the trailing-edge domain carry the same point count without either
being starved, and it is the detail that makes this topology work.

**Eight subsections (§3.1.4).** "To generate a structured mesh it is necessary to
have surfaces with four corners... To achieve that, the first airfoil is
subsectioned into eight parts." From the code (lines 470-527) the outer airfoil
splits at the trailing edge, **mid-chord** on each surface, and the nose transition;
the inner airfoil splits to match. Mid-chord is a real split: it lets the fore and
aft halves carry opposite progressions.

**Progression (§§1.1.2, 3.1.4).** Points follow a geometric series, and "on these
curves, the number of nodes is highest towards the nose and towards the Trailing
Edge to achieve a good resolution of the important parts while simultaneously saving
nodes in the less aerodynamically complicated middle."

**This one is implemented and DEFAULTED OFF (`ratio = 1.0`), measured.** On the
AERIS BWB it degrades the mesh monotonically, and badly:

    ratio 1.00   min scaled Jac  +0.45487   skew 0.699   range  842
    ratio 1.05                   +0.00508   skew 0.997   range 1283
    ratio 1.12                   -0.05444   skew 0.999   range 2118

Clustering toward the ends shrinks the cells at exactly the two places this
geometry is already tightest — a 0.0042-chord nose domain and a 0.005-chord blunt
base — and the long centre domain then has to interpolate across the resulting
mismatch. The paper's blade has a proportionally much thicker trailing edge, so the
same clustering costs it less. Kept as a knob at 1.0 so the finding is
reproducible.

**Cell-size matching (§3.1.4, eq 3.2-3.4).** Node counts on the nose edge and on the
connection lines are computed so the first step of one curve equals the cell size of
its neighbour — "the bordering cells on each side of the lines have the same size".

================================================================================
WHAT THE PAPER DOES NOT DELIVER — decisive for this study
================================================================================

**Openblademesh never achieved a pyHyp extrusion of the whole wing.** §4.1: "This
approach was not available at moment of publication and therefore the extrusion with
Pyhyp was not enabled as a standalone. **While the wingtip on its own can be meshed
with Pyhyp the whole wing can only be meshed by software with different extrusion
methods such as pointwise.**" §3.1.7 gives the reason: "Pyhyp cannot extrude the
whole wing for too big step size differences between the wingtip and the wing."

That is ADR-0010, reached independently by this study and confirmed by its source.

**The spanwise law that would fix it is stated but unimplemented.** §3.1.5 gives
equations 3.5-3.10 for one geometric series spanning the whole wing, then: "the
algebraic solution approach takes too long and the numerical approach is yet to be
finished so the formula is given here **but is not used**." The implemented fallback
is a negative exponential (eq 3.11) the paper itself calls "coarser" and "not
sufficient" on its own NREL 5MW example.

**§4.2.3 supplies the number this study lacked:** cell growth "must not exceed a
factor between 1.3 and 1.6" for stable extrusion, and Openblademesh has "no option
to set a maximum value or a range in the current version."

So S1 inherits a validated *tip* topology and an explicitly unfinished spanwise law.
The tip is implemented faithfully; the growth limit §4.2.3 names but cannot enforce
is enforced here. `STUDY.md` §1 records the split.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

STUDIES = Path(__file__).resolve().parents[1]
REPO_ROOT = STUDIES.parents[1]
for _p in (str(REPO_ROOT / "src"), str(STUDIES)):
    if _p not in sys.path:
        sys.path.insert(0, _p)

from shared.ingestion import (  # noqa: E402
    MeshBuildError,
    SurfaceBlock,
    _map_sides_to_wing,
    _tfi_patch,
    section_loop_2d,
)
from shared.qc import orient_blocks_consistently, orient_patches_2d  # noqa: E402

Array = np.ndarray

STRATEGY_ID = "S1_TIP_FIRST_SWEEP"

#: Paper §3.1.4, code line 273.
X_DILATION = 0.33
#: Paper code line 407: `1.4142 * 0.003 * sf`. sqrt(2) is the 45-degree factor.
NOSE_END_FRAC = float(np.sqrt(2.0) * 0.003)
#: Paper code line 403: the inner aft station is pulled forward by TE/4.
TE_END_TE_FRACTION = 0.25
TE_THICKNESS_ABS_M = 0.001  # DECISION-0004: constant absolute, not a chord fraction
#: Paper §4.2.3.
GROWTH_LIMIT = 1.15

LEVELS = {
    "L1_coarse": dict(chord_points=25, end_points=3, collar_points=5, target_cell_m=0.020),
    "L2_smoke": dict(chord_points=33, end_points=3, collar_points=7, target_cell_m=0.015),
    "L3_medium": dict(chord_points=49, end_points=3, collar_points=9, target_cell_m=0.010),
    "L4_fine": dict(chord_points=65, end_points=5, collar_points=13, target_cell_m=0.008),
    "L5_production": dict(chord_points=97, end_points=5, collar_points=17, target_cell_m=0.006),
}


# ---------------------------------------------------------------------------
# §1.1.2 Progression
# ---------------------------------------------------------------------------


def progression(n: int, ratio: float, *, both_ends: bool = False) -> Array:
    """Normalised geometric point distribution, paper §1.1.2 eq 1.1-1.3.

    ``both_ends`` gives the two-directional progression §3.1.4 asks for on the long
    chord curves: dense at the aerodynamically interesting end, coarse toward
    mid-chord.
    """
    if n < 2:
        raise MeshBuildError("progression needs at least 2 points.")
    if abs(ratio - 1.0) < 1e-12:
        return np.linspace(0.0, 1.0, n)
    if both_ends:
        s = progression(n, ratio, both_ends=False)
        return 0.5 * (s + (1.0 - s[::-1]))
    steps = ratio ** np.arange(n - 1)
    cum = np.concatenate([[0.0], np.cumsum(steps)])
    return cum / cum[-1]


def _resample_at(curve: Array, t: Array) -> Array:
    """Resample a polyline at normalised arc-length positions ``t``."""
    seg = np.linalg.norm(np.diff(curve, axis=0), axis=1)
    cum = np.concatenate([[0.0], np.cumsum(seg)])
    total = cum[-1] or 1.0
    tt = t * total
    return np.column_stack([np.interp(tt, cum, curve[:, i]) for i in range(curve.shape[1])])


# ---------------------------------------------------------------------------
# §3.1.4 inner airfoil and the 45-degree end stations
# ---------------------------------------------------------------------------


def _surfaces(coords: Array, le_index: int):
    return coords[: le_index + 1][::-1], coords[le_index:]  # LE->upper TE, LE->lower TE


def inner_airfoil(coords: Array, le_index: int, xq: Array, *, dilation: float):
    """Paper §3.1.4 / code lines 294-343: the third-thickness inner airfoil."""
    upper, lower = _surfaces(coords, le_index)
    zu = np.interp(xq, upper[:, 0], upper[:, 1])
    zl = np.interp(xq, lower[:, 0], lower[:, 1])
    t = zu - zl
    return zu - dilation * t, zl + dilation * t


def end_stations(
    coords: Array, le_index: int, *, end_scale: float = 1.0
) -> tuple[float, float]:
    """The two 45-degree end stations, paper code lines 403 and 407.

    **DEVIATION FROM THE PAPER, recorded as one.** ``end_scale`` widens both end
    domains by a common factor. The paper's constants are blade-specific: the nose
    station is ``sqrt(2)*0.003*chord`` (0.42% of chord) and the aft station is
    ``te_thickness/4`` (0.125% of chord here). On the NREL 5MW rotor blade the blunt
    trailing edge is proportionally far thicker, so those domains are a reasonable
    size. On this BWB section they are two to three orders of magnitude finer than
    the mid-chord cells, which is the whole of S1's cell-size range problem —
    measured **754-897** against the 99-140 that has actually marched, and
    min-cell/`s0` of **2.1** where Stage 02's S1 exploded at 0.9.

    ``end_scale = 1.0`` reproduces the paper exactly and stays the reference. The
    default is **5.0**, which is where the cell-size range bottoms out:

        end_scale   min scaled Jac   range   min cell   est min/s0
            1.0        +0.45487      810.0    26.6 um       2.1     EXPLODED
            2.0        +0.46939      421.1    51.1 um       4.0
            3.0        +0.35330      280.6    76.7 um       6.1
            5.0        +0.24199     *172.7*  124.6 um       9.8     <- default
            8.0        +0.14195      200.8   140.6 um      11.1
           12.0        +0.07613      231.8   162.3 um      12.8

    At 1.0 — the paper exactly — the march explodes at layer 2 with a minimum
    volume of -7.33e+62, the same signature Stage 02's S1 produced at min-cell/s0
    of 0.9. The paper predicts this itself in section 3.1.7.
    """
    upper, lower = _surfaces(coords, le_index)
    x_le, x_te = float(upper[0, 0]), float(upper[-1, 0])
    chord = x_te - x_le
    te_abs = float(upper[-1, 1] - lower[-1, 1])
    x_nose = x_le + end_scale * NOSE_END_FRAC * chord
    x_aft = x_te - end_scale * TE_END_TE_FRACTION * te_abs
    if not (x_le < x_nose < x_aft < x_te):
        raise MeshBuildError(
            f"45-degree end stations out of order: le {x_le}, nose {x_nose}, "
            f"aft {x_aft}, te {x_te}"
        )
    return x_nose, x_aft


def _straight(p0: Array, p1: Array, n: int) -> Array:
    s = np.linspace(0.0, 1.0, n)[:, None]
    return (1.0 - s) * p0 + s * p1


def _point_on(curve: Array, x: float) -> Array:
    return np.array([x, float(np.interp(x, curve[:, 0], curve[:, 1]))])


def outer_station_at_45(surface: Array, inner_pt: Array, x_hi: float) -> float:
    """x on ``surface`` where the line to ``inner_pt`` makes 45 degrees.

    Paper §3.1.4: "The points for the end of the splines are created so that the
    connection lines from these to the outer airfoil are 45 degrees. The 45 degrees
    are important because they allow for the most regular translation of cells on
    each side of the connecting line."

    Solving it is what the rule is FOR. Splitting the outer arc at the inner
    point's own x instead makes the connection line vertical — and near the leading
    edge the contour is itself nearly vertical, so the two run collinear and the
    corner cell degenerates. Measured with the naive split: `tip_nose` skewness
    **1.000**, min scaled Jacobian **-0.000**. This is the same ~180-degree corner
    ADR-0006 identified for cap4, arrived at from the opposite direction.

    45 degrees means |dx| == |dz|, so the root of

        f(x) = (x - x_i) - |z(x) - z_i|

    is sought between the inner station and ``x_hi`` by bisection.
    """
    x_i, z_i = float(inner_pt[0]), float(inner_pt[1])

    def f(x: float) -> float:
        return (x - x_i) - abs(float(np.interp(x, surface[:, 0], surface[:, 1])) - z_i)

    lo, hi = x_i + 1e-9, float(x_hi)
    if f(hi) < 0.0:
        return hi
    for _ in range(80):
        mid = 0.5 * (lo + hi)
        if f(mid) > 0.0:
            hi = mid
        else:
            lo = mid
    return 0.5 * (lo + hi)


# ---------------------------------------------------------------------------
# §3.1.4 the subsection and the tip domains
# ---------------------------------------------------------------------------


def section_geometry(
    coords: Array,
    le_index: int,
    *,
    chord_points: int,
    end_points: int,
    ratio: float,
    end_scale: float = 1.0,
) -> dict:
    """The six outer arcs and four inner arcs of one section.

    Outer, in ring order from the upper trailing edge:

        upper_aft   upper TE corner -> mid-chord
        upper_fore  mid-chord       -> nose station
        nose        upper nose      -> around LE -> lower nose
        lower_fore  nose station    -> mid-chord
        lower_aft   mid-chord       -> lower TE corner
        base        lower TE corner -> upper TE corner   (the blunt trailing edge)
    """
    upper, lower = _surfaces(coords, le_index)
    x_le, x_te = float(upper[0, 0]), float(upper[-1, 0])
    x_nose, x_aft = end_stations(coords, le_index, end_scale=end_scale)
    x_mid = 0.5 * (x_le + x_te)

    def _arc(curve: Array, xa: float, xb: float, n: int) -> Array:
        lo, hi = min(xa, xb), max(xa, xb)
        mask = (curve[:, 0] > lo) & (curve[:, 0] < hi)
        mid = curve[mask]
        if xb < xa:
            mid = mid[::-1]
        seg = np.vstack([_point_on(curve, xa), mid, _point_on(curve, xb)])
        # Dense toward the aerodynamically interesting end (§3.1.4): the aft
        # halves cluster at the trailing edge, the fore halves at the nose.
        return _resample_at(seg, progression(n, ratio))

    # Paper code line 408: `Inter_X[3] = 0.5 * Inter_X[2]`. The OUTER nose split
    # sits at HALF the inner nose station — i.e. FORWARD of it, nearer the leading
    # edge — so the connection line runs aft-and-inward at roughly 45 degrees.
    #
    # Both other readings were tried and are worse:
    #   * outer split at the inner station  -> connection line vertical, collinear
    #     with a near-vertical contour: `tip_nose` skew 1.000, jac -0.000
    #   * outer split solved AFT for |dx|==|dz| -> line points forward against the
    #     inner edge: jac -0.816 to -0.902
    # Reading the listing rather than inferring the rule is what settled it.
    x_no_up = x_le + 0.5 * (x_nose - x_le)
    x_no_lo = x_no_up
    nose_up = upper[(upper[:, 0] <= x_no_up)]
    nose_lo = lower[(lower[:, 0] <= x_no_lo)]
    o_nose = np.vstack([
        _point_on(upper, x_no_up), nose_up[::-1], nose_lo[1:], _point_on(lower, x_no_lo),
    ])

    outer = {
        "upper_aft": _arc(upper, x_te, x_mid, chord_points),
        "upper_fore": _arc(upper, x_mid, x_no_up, chord_points),
        "nose": _resample_at(o_nose, np.linspace(0.0, 1.0, end_points)),
        "lower_fore": _arc(lower, x_no_lo, x_mid, chord_points),
        "lower_aft": _arc(lower, x_mid, x_te, chord_points),
        "base": _straight(lower[-1], upper[-1], end_points),
    }

    def _inner(xa: float, xb: float, n: int, up: bool) -> Array:
        xq = xa + (xb - xa) * progression(n, ratio)
        iu, il = inner_airfoil(coords, le_index, xq, dilation=X_DILATION)
        return np.column_stack([xq, iu if up else il])

    iu_n, il_n = inner_airfoil(coords, le_index, np.array([x_nose]), dilation=X_DILATION)
    iu_a, il_a = inner_airfoil(coords, le_index, np.array([x_aft]), dilation=X_DILATION)
    inner = {
        "upper_aft": _inner(x_aft, x_mid, chord_points, True),
        "upper_fore": _inner(x_mid, x_nose, chord_points, True),
        "nose": _straight(np.array([x_nose, iu_n[0]]), np.array([x_nose, il_n[0]]), end_points),
        "lower_fore": _inner(x_nose, x_mid, chord_points, False),
        "lower_aft": _inner(x_mid, x_aft, chord_points, False),
        "base": _straight(np.array([x_aft, il_a[0]]), np.array([x_aft, iu_a[0]]), end_points),
    }
    return {
        "outer": outer, "inner": inner,
        "x_le": x_le, "x_te": x_te, "x_nose": x_nose, "x_aft": x_aft, "x_mid": x_mid,
    }


ARC_ORDER = ("upper_aft", "upper_fore", "nose", "lower_fore", "lower_aft", "base")


def tip_domains_2d(geom: dict, *, collar_points: int) -> tuple[list[Array], dict]:
    """The paper's seven wingtip domains, all four-cornered (§3.1.4)."""
    outer, inner = geom["outer"], geom["inner"]
    patches, names = [], []
    for key in ARC_ORDER:
        o, i = outer[key], inner[key]
        if len(o) != len(i):
            raise MeshBuildError(f"{key}: outer {len(o)} vs inner {len(i)} points")
        patches.append(
            _tfi_patch(
                bottom=o, top=i,
                left=_straight(o[0], i[0], collar_points),
                right=_straight(o[-1], i[-1], collar_points),
            )
        )
        names.append(f"tip_{key}")

    # The centre, bounded by the four long inner arcs and the two short end edges.
    inner_low = np.vstack([inner["lower_fore"], inner["lower_aft"][1:]])   # nose -> aft
    inner_up = np.vstack([inner["upper_fore"][::-1], inner["upper_aft"][::-1][1:]])
    patches.append(
        _tfi_patch(
            bottom=inner_low, top=inner_up,
            left=inner["nose"][::-1], right=inner["base"],
        )
    )
    names.append("tip_centre")

    patches, flipped = orient_patches_2d(patches)
    info = {
        "topology": "openblademesh_inner_airfoil_seven_domain",
        "block_names": names,
        "dilation_X": X_DILATION,
        "nose_end_frac_of_chord": float((geom["x_nose"] - geom["x_le"]) / (geom["x_te"] - geom["x_le"])),
        "te_end_frac_of_chord": float((geom["x_te"] - geom["x_aft"]) / (geom["x_te"] - geom["x_le"])),
        "collar_points": int(collar_points),
        "orientation_flipped": flipped,
        "source": "Openblademesh §3.1.4: X=0.33, sqrt(2)*0.003 nose, TE/4 aft, mid-chord split",
    }
    return patches, info


# ---------------------------------------------------------------------------
# §3.1.5 spanwise
# ---------------------------------------------------------------------------


def spanwise_counts(
    lengths: list[float], *, target_cell: float, growth_limit: float = GROWTH_LIMIT,
    minimum: int = 2,
) -> list[int]:
    """Cells per spanwise interval, growth-limited.

    The paper's implemented rule is eq 3.11 (a negative exponential), which it calls
    "coarser" and "not sufficient". Equations 3.5-3.10 give the intended single
    geometric series and are explicitly **not used** in the source. What is added
    here is the growth limit §4.2.3 names (1.3-1.6) and says Openblademesh cannot
    enforce — the direct answer to the §3.1.7 failure where pyHyp refuses the whole
    wing because tip-to-wing step size differs too much.
    """
    raw = [max(minimum, int(round(length / max(target_cell, 1e-12)))) for length in lengths]
    for _ in range(len(raw) * 4):
        changed = False
        for i in range(len(raw) - 1):
            hi, lo = max(raw[i], raw[i + 1]), min(raw[i], raw[i + 1])
            if hi > lo * growth_limit:
                capped = max(minimum, int(np.ceil(lo * growth_limit)))
                if raw[i] > raw[i + 1]:
                    raw[i] = capped
                else:
                    raw[i + 1] = capped
                changed = True
        if not changed:
            break
    return raw


def spanwise_counts_tip_anchored(
    lengths: list[float],
    *,
    first_cell: float,
    growth: float,
    max_cell: float,
    minimum: int = 1,
) -> list[int]:
    """Equations 3.5-3.10: ONE geometric series over the whole wing, anchored at the tip.

    This is the law Openblademesh gives in full and then states it does not use —
    "the algebraic solution approach takes too long and the numerical approach is yet
    to be finished so the formula is given here but is not used" (§3.1.5) — and whose
    absence is the reason it reports "Pyhyp cannot extrude the whole wing for too big
    step size differences between the wingtip and the wing" (§3.1.7).

    §3.1.5 states the requirement plainly: "it is important to generate cells on the
    wing towards the wingtip which are as similar as possible to the cells on the
    wingtip on the edge. Because the wingtip will have very small cells, especially
    at the Trailing Edge, the cells on the wing need to be very small. However, if
    this cell dimension would be consistent over the whole wing the computational
    load would be enormous."

    So: start at the tip with ``first_cell`` — the tip cap's own radial cell size —
    and grow inboard by ``growth`` per cell (§4.2.3 bounds this at 1.3-1.6) until
    ``max_cell``. Solved by walking rather than algebraically, which is what the
    source found too slow.

    ``lengths`` is ordered root -> tip, so the walk consumes it in reverse.

    ``spanwise_first_cell_factor`` scales the tip cap's median radial cell to set the
    first spanwise cell. Measured against the tip/OML size jump, which is what
    section 3.1.5 asks to close:

        factor 0.50  ->  outboard cell 2186 um,  jump 3.86
        factor 0.25  ->                1165 um,  jump 2.06
        factor 0.12  ->                 558 um,  jump 0.99   <- default
        factor 0.06  ->                 272 um,  jump 0.48

    0.12 lands the outboard spanwise cell on the tip cap's own radial cell size.
    The factor is below 1 because the probe takes the MEDIAN radial cell over the
    cap's collars while the jump that matters is against the smallest of them.

    **Why it matters, measured.** Without it the outboard spanwise cells were
    14-21 mm against tip-cap radial cells of 0.13-1.0 mm — a 28:1 jump straight
    across the tip interface — and pyHyp produced a negative volume in layer 2 and
    diverged, twice, at both `end_scale` 1.0 and 5.0.
    """
    out: list[Array] = []
    size = float(first_cell)
    for length in reversed(lengths):
        length = float(length)
        # Walk outboard-to-inboard laying down cells of the running size. The
        # positions, not just the count, must follow the series: placing n cells
        # UNIFORMLY inside the interval throws the progression away and leaves the
        # outboard cell as large as before. That was measured — the tip/OML size
        # jump stayed at 33.8 until the positions were carried through.
        edges, acc, n = [0.0], 0.0, 0
        while acc + size < length and n < 100000:
            acc += size
            edges.append(acc)
            n += 1
            size = min(size * growth, max_cell)
        if len(edges) < minimum + 1:
            edges = list(np.linspace(0.0, length, minimum + 1))[:-1]
            acc = edges[-1]
        # Fractions measured from the OUTBOARD end, flipped into the interval's own
        # root->tip parameterisation. `edges[0] == 0` is the OUTBOARD end, i.e.
        # fraction 1.0 — that is the NEXT station's own column, so it must be
        # dropped or every interval boundary gets a duplicated, zero-length
        # spanwise edge (measured: min scaled Jacobian 0.0, cell-size range inf).
        # Rescale so the series fills the interval EXACTLY. Folding the leftover
        # into the final cell instead lets that cell exceed `max_cell` — measured,
        # the root interval's last cell reached 26.8 mm against a 15 mm cap and the
        # cell-size range went UP, 172.7 -> 214.8. Rescaling preserves the shape of
        # the progression and respects the cap.
        e = np.asarray(edges, dtype=float)
        e = e / (e[-1] or 1.0)
        frac = 1.0 - e[1:]
        frac = np.concatenate([[0.0], frac[frac > 1e-9]])
        out.append(np.unique(frac))
    return list(reversed(out))


def sweep_tip_to_root(blocks: list[Array], fractions_per_interval) -> list[Array]:
    """Subdivide each spanwise interval at the given fractions, tip-first (§3.1.5).

    ``fractions_per_interval[j]`` holds the normalised positions inside interval j,
    starting at 0.0 and excluding 1.0 (which is the next station's own column).
    Accepting positions rather than counts is what lets the global geometric series
    of eq 3.5-3.10 actually reach the mesh.
    """
    n_int = blocks[0].shape[1] - 1
    if len(fractions_per_interval) != n_int:
        raise MeshBuildError(f"law gives {len(fractions_per_interval)}, blocks have {n_int}")
    out = []
    for blk in blocks:
        cols = []
        for j, fracs in enumerate(fractions_per_interval):
            for s in np.atleast_1d(fracs):
                cols.append((1.0 - s) * blk[:, j, :] + s * blk[:, j + 1, :])
        cols.append(blk[:, -1, :])
        out.append(np.stack(cols, axis=1))
    return out


def map_patch_2d_to_tip(wing, patch_2d: Array) -> Array:
    n_xsec = len(wing.xsecs)
    sides = [[patch_2d[i] for i in range(patch_2d.shape[0])] for _ in range(n_xsec)]
    return np.stack([m[:, -1, :] for m in _map_sides_to_wing(wing, sides)], axis=0)


# ---------------------------------------------------------------------------
# Build
# ---------------------------------------------------------------------------

OML_NAMES = [f"oml_{k}" for k in ARC_ORDER]


def _resample_oml_spanwise(blocks: list[SurfaceBlock], span_cells: int) -> list[SurfaceBlock]:
    """Resample only OML columns while preserving every tip-cap block exactly."""
    if span_cells < 2:
        raise MeshBuildError("span_cells must be at least two")
    out: list[SurfaceBlock] = []
    for block in blocks:
        if not block.name.startswith("oml_") or block.xyz.shape[1] == span_cells + 1:
            out.append(block)
            continue
        old_t = np.linspace(0.0, 1.0, block.xyz.shape[1])
        new_t = np.linspace(0.0, 1.0, span_cells + 1)
        xyz = np.stack(
            [np.column_stack([np.interp(new_t, old_t, block.xyz[i, :, axis]) for axis in range(3)])
             for i in range(block.xyz.shape[0])],
            axis=0,
        )
        out.append(SurfaceBlock(name=block.name, xyz=xyz, family=block.family))
    return out


def build_surface(
    wing,
    *,
    level: str = "L2_smoke",
    te_thickness_abs_m: float = TE_THICKNESS_ABS_M,
    ratio: float = 1.0,
    end_scale: float = 5.0,
    tip_anchored_spanwise: bool = True,
    spanwise_first_cell_factor: float = 0.12,
    growth_limit: float = GROWTH_LIMIT,
    realise_law: bool = True,
    span_cells: int | None = None,
    **overrides,
) -> tuple[list[SurfaceBlock], dict]:
    """Build S1: 6 OML blocks swept tip-to-root plus the 7-domain tip."""
    if level not in LEVELS:
        raise MeshBuildError(f"unknown level {level!r}; known: {sorted(LEVELS)}")
    cfg = dict(LEVELS[level])
    cfg.update({k: v for k, v in overrides.items() if v is not None})

    xsecs = list(wing.xsecs)
    if len(xsecs) < 3:
        raise MeshBuildError("S1 needs at least three spanwise stations.")

    sides_by_xsec, tip_geom = [], None
    for xsec in xsecs:
        coords, le_index = section_loop_2d(xsec, te_thickness_abs_m=te_thickness_abs_m)
        g = section_geometry(
            coords, le_index,
            chord_points=cfg["chord_points"], end_points=cfg["end_points"], ratio=ratio,
            end_scale=end_scale,
        )
        tip_geom = g
        sides_by_xsec.append([g["outer"][k] for k in ARC_ORDER])

    oml = _map_sides_to_wing(wing, sides_by_xsec)

    le_line = np.asarray(
        wing.mesh_line(x_nondim=[0.0] * len(xsecs), z_nondim=[0.0] * len(xsecs), add_camber=False)
    )
    lengths = [float(np.linalg.norm(le_line[i + 1] - le_line[i])) for i in range(len(xsecs) - 1)]
    if tip_anchored_spanwise:
        # First spanwise cell matched to the tip cap's own radial cell (§3.1.5).
        cap_probe, _ = tip_domains_2d(tip_geom, collar_points=cfg["collar_points"])
        radial = []
        for patch in cap_probe[:-1]:
            d = np.linalg.norm(np.diff(patch, axis=1), axis=2)
            radial.append(float(np.median(d)))
        first_cell = float(np.median(radial)) * spanwise_first_cell_factor
        counts = spanwise_counts_tip_anchored(
            lengths, first_cell=first_cell, growth=growth_limit,
            max_cell=cfg["target_cell_m"],
        )
    else:
        counts = [
            np.linspace(0.0, 1.0, n + 1)[:-1]
            for n in spanwise_counts(
                lengths, target_cell=cfg["target_cell_m"], growth_limit=growth_limit
            )
        ]
    if realise_law:
        oml = sweep_tip_to_root(oml, counts)

    blocks = [SurfaceBlock(name=n, xyz=b, family="wall") for n, b in zip(OML_NAMES, oml, strict=True)]

    native_span_cells = int(sum(len(np.atleast_1d(c)) for c in counts))
    if span_cells is not None and int(span_cells) != native_span_cells:
        blocks = _resample_oml_spanwise(blocks, int(span_cells))

    cap_2d, cap_info = tip_domains_2d(tip_geom, collar_points=cfg["collar_points"])
    blocks += [
        SurfaceBlock(name=n, xyz=map_patch_2d_to_tip(wing, p), family="wall")
        for n, p in zip(cap_info["block_names"], cap_2d, strict=True)
    ]

    blocks, orientation = orient_blocks_consistently(blocks)
    info = {
        "strategy_id": STRATEGY_ID,
        "level": level,
        "level_settings": cfg,
        "te_thickness_abs_m": te_thickness_abs_m,
        "progression_ratio": ratio,
        "end_scale": end_scale,
        "sweep_direction": "tip_to_root",
        "oml_block_names": OML_NAMES,
        "tip_block_names": cap_info["block_names"],
        "tip_closure": cap_info["topology"],
        "tip_cap_info": cap_info,
        "orientation": orientation,
        "spanwise": {
            "target_cell_m": cfg["target_cell_m"],
            "growth_limit": growth_limit,
            "segment_lengths_m": lengths,
            "cells_per_interval": [int(len(np.atleast_1d(c))) for c in counts],
            "realised": bool(realise_law),
            "spanwise_cells": int(span_cells) if span_cells is not None else native_span_cells,
            "requested_span_cells": int(span_cells) if span_cells is not None else None,
            "realized_span_cells": int(span_cells) if span_cells is not None else native_span_cells,
            "native_stations": len(xsecs),
        },
        "source": "Openblademesh (Heider 2023) §3.1.4, followed faithfully",
    }
    return blocks, info
