"""Cross-machine live status board for long-running CFD commands.

There is no live link between two independent Claude Code / CLI sessions on
separate machines (e.g. a Linux laptop and a Windows/WSL2 desktop) -- git is
the only channel. `record_status()` is called by long-running commands
(study run, campaign mesh-robustness, campaign surface-option-sweep) at
start, at each meaningful progress step, and at the end. State lives in
`configs/cfd/status_state.json` (small, tracked in git, one row per job);
`configs/cfd/STATUS.md` is regenerated from it on every call. Commit +
push/pull that pair and the other machine sees current progress -- not
live, but current as of the last commit, with no manual bookkeeping.
"""

from __future__ import annotations

import json
import socket
import subprocess
from datetime import datetime, timezone
from pathlib import Path

from aeris.common.paths import CONFIGS_DIR, PROJECT_ROOT

STATUS_DIR = CONFIGS_DIR / "cfd"
STATE_PATH = STATUS_DIR / "status_state.json"
MD_PATH = STATUS_DIR / "STATUS.md"


def _git_commit() -> str:
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            cwd=PROJECT_ROOT,
            capture_output=True,
            text=True,
            timeout=5,
        )
        commit = result.stdout.strip()
        return commit if commit else "unknown"
    except (OSError, subprocess.SubprocessError):
        return "unknown"


def _load_state() -> dict[str, dict[str, object]]:
    if not STATE_PATH.is_file():
        return {}
    try:
        return json.loads(STATE_PATH.read_text(encoding="utf-8"))
    except (json.JSONDecodeError, OSError):
        return {}


def record_status(
    job_id: str,
    *,
    kind: str,
    status: str,
    progress: str,
    detail: str = "",
    workdir: Path | None = None,
) -> None:
    """Upsert one job's row in status_state.json and regenerate STATUS.md.

    job_id should be stable across calls for the same run (e.g. the
    campaign/study workdir name) so repeated calls update one row.
    """
    STATUS_DIR.mkdir(parents=True, exist_ok=True)
    state = _load_state()
    previous = state.get(job_id, {})

    state[job_id] = {
        "kind": kind,
        "status": status,
        "progress": progress,
        "detail": detail,
        "machine": socket.gethostname(),
        "commit": _git_commit(),
        "workdir": str(workdir) if workdir is not None else previous.get("workdir"),
        "updated_utc": datetime.now(timezone.utc).isoformat(timespec="seconds"),
    }
    STATE_PATH.write_text(json.dumps(state, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    _render_markdown(state)


def _render_markdown(state: dict[str, dict[str, object]]) -> None:
    lines = [
        "# AERIS CFD — Live Status",
        "",
        "Auto-generated by `aeris cfd study run` / `aeris cfd campaign *` -- do",
        "not edit by hand. No live connection: this reflects the last update",
        "that was committed on whichever machine ran it. `git pull` to refresh.",
        "",
        "| Job | Kind | Status | Progress | Machine | Commit | Updated (UTC) |",
        "|---|---|---|---|---|---|---|",
    ]
    for job_id, row in sorted(
        state.items(), key=lambda kv: str(kv[1].get("updated_utc", "")), reverse=True
    ):
        lines.append(
            f"| {job_id} | {row.get('kind', '')} | {row.get('status', '')} | "
            f"{row.get('progress', '')} | {row.get('machine', '')} | "
            f"{row.get('commit', '')} | {row.get('updated_utc', '')} |"
        )
    detail_lines = [
        f"- **{job_id}**: {row['detail']}"
        for job_id, row in state.items()
        if row.get("detail")
    ]
    if detail_lines:
        lines += ["", "## Detail", ""] + detail_lines
    MD_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")
