"""
SU2 ``.cfg`` generation from resolved effective options.

Formatting rules (SU2 config conventions):

* booleans → ``YES`` / ``NO``
* lists/tuples → ``( a, b, c )``
* everything else → ``str(value)`` (strings pass verbatim, so marker
  expressions like ``( wall, 0.0 )`` can be provided pre-formatted)

Keys are written sorted for deterministic, diffable configs; each line is
annotated with its provenance source as a trailing comment — the config
file itself carries the audit trail.
"""

from __future__ import annotations

from pathlib import Path

from aeris.cfd.options.layers import EffectiveOptions


def format_su2_value(value: object) -> str:
    if isinstance(value, bool):
        return "YES" if value else "NO"
    if isinstance(value, (list, tuple)):
        return "( " + ", ".join(format_su2_value(item) for item in value) + " )"
    return str(value)


def write_su2_cfg(path: Path, effective: EffectiveOptions, *, header: str = "") -> Path:
    lines = ["% Auto-generated by aeris.cfd — do not hand-edit; options are"]
    lines.append("% resolved with provenance in su2_effective_options.json.")
    if header:
        lines.extend(f"% {line}" for line in header.splitlines())
    for key in sorted(effective.values):
        value = format_su2_value(effective.values[key])
        source = effective.provenance.get(key, "unknown")
        lines.append(f"{key}= {value}  % {source}")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return path
